### ISSUE TITLE
Out of memory issues with gradient accumulation

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#523]
This is because the temporary gradients are kept around in the gradients object.

Is it possible to have gradients object clear temporary gradients?

We could do something like:

```rust
// would set some flags on which gradients are not temporary
let grads: Gradients<_, _> = model.alloc_grads();
...
let grads = loss.backward(); // backward would clear the temporary gradients after running
```

**Comment by coreylowman** [comment]
Another possible solution: Have backward ops register what tensor ids they need, and then drop the gradients after they are no longer needed by the backward op

**Comment by coreylowman** [comment]
Would it be possible for the backward ops themselves to free the gradients? Each backward op could register itself as one that needs certain tensor gradients, and then once the backward op completes it could decrement some registry counter.

Unclear how this would interact with model parameter gradients though

**Comment by coreylowman** [comment]
This was not resolved actually. Repo is https://github.com/jafioti/lm_test, and more details are:

> > - batch size 32 with batch accum 1 works
> >  - batch size 64 with batch accum 1 works
> >  - batch size 32 with batch accum 2 is work
>
> Actually that works, but when I set batch accum to 5 it starts giving me OOM errors. batch accum 4 works, so I think it's still leaking memory.
> Here's the error I get: Err(Driver(DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")))

**Comment by coreylowman** [comment]
I'm not seeing any obvious signs of memory leaking. Here's the script I was using:

```rust
#![feature(generic_const_exprs)]

use dfdx::{optim::Adam, prelude::*};

fn main() {
    let dev: Cuda = Default::default();

    const BATCH: usize = 64;
    const SEQ: usize = 32;
    const VOCAB: usize = 30527;

    type Model = (
        Embedding<VOCAB, 512>,
        TransformerEncoder<512, 16, 1024, 8>,
        Linear<512, VOCAB>,
    );

    let mut model = dev.build_module::<Model, f32>();
    let mut grads = model.alloc_grads();
    let mut opt = Adam::new(&model, Default::default());

    let x: Tensor<Rank2<BATCH, SEQ>, usize, _> = dev.zeros();
    let y: Tensor<Rank3<BATCH, SEQ, VOCAB>, f32, _> = dev.sample_normal().softmax::<Axis<2>>();

    let accum = 10;
    for i in 0.. {
        let logits = model.forward_mut(x.trace_into(grads));
        let loss = cross_entropy_with_logits_loss(logits, y.clone());
        let v = loss.array();
        grads = loss.backward();
        if i % accum == 0 {
            opt.update(&mut model, &grads);
            model.zero_grads(&mut grads);
        }
    }
}
```

**Comment by jafioti** [comment]
Ok I got some more info now. It seems it is only running out of memory once update is called, not when it is accumulating gradients.

Here's  the Nsight report:
 https://drive.google.com/file/d/1x2M8Wk3Vt_puwNo2JIgqdt0uAWgs-MJB/view?usp=share_link

**Comment by coreylowman** [comment]
I'll try reproducing again this weekend most likely

**Comment by coreylowman** [comment]
@jafioti can you check with latest main (cudarc 0.9.0). I *think* the issue should be resolved (I was able to see large memory usage reduction in general)

**Comment by jafioti** [comment]
Ok will do

**Comment by jafioti** [comment]
@coreylowman  I'm still getting OOMs when I run with more than 1 grad accum. Some memory must still be getting accumulated.

**Comment by coreylowman** [comment]
@jafioti can you add some print statements if the loop continues due to an error? I'm wondering if something happens where an error occurs, which then means the gradients you've previously allocated are not given back to you when you run `loss.backward()`? I'm not sure how to recover the gradients in this case since they would be owned by the existing tape which was lost due to the error 🤔 . But if this is happening, then the gradients you use https://github.com/jafioti/lm_test/blob/main/src/main.rs#L107 would be keeping all the non-leaf tensors around inside them, which could explain this.

Could you try doing an `gradients.get_or_insert_with(|| model.alloc_grads())` instead of doing the `x.traced()`?

**Comment by jafioti** [comment]
@coreylowman 
> Could you try doing an gradients.get_or_insert_with(|| model.alloc_grads()) instead of doing the x.traced()?

How would this work? In `gradients.get_or_insert_with(|| model.alloc_grads())` x/input isn't referenced. How would it be inputted?

**Comment by jafioti** [comment]
I'm a fool. So I found the issue, and it has to do with my Option<Gradients> system. So for background, I use the Option<Gradient> so that I would be able to `continue` when an issue with the fallible functions happened. I replace the `Option<Gradients>` with `None` at the beginning when I merge the grads with the input, and then once I do `.backward()` I put the gradients back in. This is so that if anything goes wrong before the backward call the gradients will just be set to None and reallocated on the next loop.

The issue is that when I called the optimizer, this is the code:
```rust
if left % BATCH_ACCUM == 0 {
    if let Some(mut gradients) = Option::take(&mut gradients) {
        scheduler.set_progress((total_len - left) as f32 / total_len as f32);
        scheduler.step(opt);
        if let Err(e) = opt.update(model, &gradients) {
            println!("{} {e:?}\n", "Update Error:".bold().red());
        }
        model.zero_grads(&mut gradients);
    }
}
```
Notice any issues?
I'm moving the gradients out of the `Option<Gradients>` with `Option::take()`, and I'm never putting them back, even after they're zeroed. So each time it runs the optimizer, it has to reallocate new grads next loop. So the solution is simple: just put the grads back after the optimization / zeroing:
```rust
if iter % BATCH_ACCUM == 0 {
    if let Some(mut grads) = Option::take(&mut gradients) {
        scheduler.set_progress((total_len - left) as f32 / total_len as f32);
        scheduler.step(opt);
        println!("Optim Update / Grad Zero");
        if let Err(e) = opt.update(model, &grads) {
            println!("{} {e:?}\n", "Update Error:".bold().red());
        }
        model.zero_grads(&mut grads);
        gradients = Some(grads); // Here!
    }
}
```
Now this doesn't get around the initial issue I was working on: If the forward or loss function fails, we lose the gradients! In which case we're forced to reallocate, and the existing grads go into the abyss (I'm not sure if they are freed, but given my errors I suspect not). This is a real problem because we want the training loop to be fully falliable. So there needs to be a way to give out the grads but have some way of getting them back. Perhaps `trace_into` can take a mutable reference instead of owning the grads?

Anyway this mystery is solved, on to the next.

**Comment by coreylowman** [comment]
Thinking further on this, I'm not actually sure it'd be okay to receive the gradients back. At that point you don't know what is in the gradients (e.g. maybe only half of the model parameters have been populated), and you also don't know what operations on are on the gradients.

I'm okay with the current approach being: "if your forward fails at some point, you have to re-allocate the gradients". That means the user always knows what state the gradients are on, and when people report a bug we don't have to worry about gradients being in a weird state.

I'm still contemplating if dfdx should allocate gradients (with .trace()) or make users allocate (either with `model.alloc_grads()` or with `Gradients::without_leaf_tensors()`). I'm leaning towards the latter, which I think would've made this bug at least easier to find (because you would have called `Gradients::without_leaf_tensors()`). WIll open a separate issue for this.

Will close this for now.

**Comment by jafioti** [comment]
@coreylowman What would happen if an error occurs and those grads go out of scope though? I agree you shouldn't do anything with them, but they definitely need to be freed.

**Comment by jafioti** [comment]
I lean toward the idea of user-managed grads, so you only give trace() a mut ref to the grads you allocated.

**Comment by coreylowman** [comment]
They will be freed when `Gradients` is dropped
